import React, { useState } from "react";
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

import styles from '@/styles/Home.module.css'
import { TabNavigation } from '@/components/TabNavigation'
import { client } from '@/apollo/apollo-client'

import { ActiveTabState } from '@/types/common'
import { PokemonsList } from '@/types/pokemons'
import { Query, QueryPokemonsArgs } from '@/types/graphql'
import { POKEMONS } from '@/graphql/queries.graphql'

const inter = Inter({ subsets: ['latin'] })
const POKEMON_IMAGE_SIZE = 240
const FAVOURITE_IMAGE_SIZE = 30
const favouriteDev = false

type Props = {
  pokemons: PokemonsList,
}

export async function getStaticProps(): Promise<{ props: Props }> {
  const { data } = await client.query<Query, QueryPokemonsArgs>({
    query: POKEMONS
  });

  return {
    props: {
      pokemons: data.pokemons.edges,
    }
  }
}

export default function Home({ pokemons }: Props) {
  const [activeTab, setActiveTab] = useState<ActiveTabState>('all')

  const handleAddToFavourite = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    // TODO: add to feature
  }

  return (
    <>
      <Head>
        <title>Pokemon App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <TabNavigation activeTab={activeTab} setActiveTab={setActiveTab} />

        <div className={styles.grid}>
          {pokemons.map(p => (
            <a
              key={p.id}
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                src={p.image}
                alt={p.name}
                width={POKEMON_IMAGE_SIZE}
                height={POKEMON_IMAGE_SIZE}
                priority
                className={styles.cardImage}
              />
              <h3>
                {p.name}
              </h3>
              <p>
                {p.types.toString()}
              </p>
              <button onClick={handleAddToFavourite}>
                {favouriteDev ? (
                  <Image
                    src="/images/heart-filled.png"
                    alt="favourite"
                    width={FAVOURITE_IMAGE_SIZE}
                    height={FAVOURITE_IMAGE_SIZE}
                    priority
                  />
                ) : (
                  <Image
                    src="/images/heart.png"
                    alt="favourite"
                    width={FAVOURITE_IMAGE_SIZE}
                    height={FAVOURITE_IMAGE_SIZE}
                    priority
                  />
                )}
              </button>
            </a>
          ))}
        </div>
      </main>
    </>
  )
}
