import { useState } from "react";
import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { TabNavigation } from '@/components/TabNavigation'

const inter = Inter({ subsets: ['latin'] })

export type ActiveTabState = 'all' | 'favorites'

export default function Home() {
  const [activeTab, setActiveTab] = useState<ActiveTabState>('all')

  return (
    <>
      <Head>
        <title>Pokemon App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

        <TabNavigation activeTab={activeTab} setActiveTab={setActiveTab}/>

        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
